oc_user:
    resource: "@OCUserBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

login:
    path:   /login
    defaults:  { _controller: OCUserBundle:Security:login }

login_check:
    path:   /login_check

logout:
    path:   /logout